import Head from "next/head";
import Image from 'next/image'
import Header from "../components/Header";
import Footer from "../components/Footer";
import styles from 'libs/font-awesome/css/font-awesome.min.css'
import Script from 'next/script'

export default function Home() {
  return (
    <main className="d-flex flex-column min-vh-100">
      <Head>
        <title>Mik McLean - Lead Cloud Engineer</title>
        <meta name="description" content="Generated by create next app" />

        <link rel="icon" href="/favicon.ico" />

      </Head>
      <Header />
      <Script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></Script>
      <Script type="text/javascript" src="../js/scripts.js"></Script>
      <Script type="text/javascript" src="../js/scripts.min.js"></Script>
      <div id="lead">
        <div id="lead-content">
            <h1>Mik McLean</h1>
            <h2>Lead Cloud Engineer</h2>
            <a href="#" className="btn-rounded-white">Download CV</a>
        </div>

        <div id="lead-overlay"></div>

        <div id="lead-down">
            <span>
                <i className="fa fa-chevron-down" aria-hidden="true"></i>
            </span>
        </div>
    </div>

    <div id="about">
        <div className="container">
            <div className="row">
                <div className="col-md-4">
                    <h2 className="heading">About Me</h2>
                </div>
                <div className="col-md-8">
                    <p>
                        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur in iaculis ex. Etiam volutpat laoreet urna. Morbi ut tortor nec nulla commodo malesuada sit amet vel lacus. Fusce eget efficitur libero. Morbi dapibus porta quam laoreet placerat. Donec
                        eu vehicula neque. Donec viverra lorem nunc, tempus euismod eros sollicitudin ut. Quisque et tincidunt libero. Donec id pharetra justo. Proin euismod lacinia dolor, eu scelerisque justo tempus pharetra. Vivamus nunc justo, finibus
                        ut nisl sed, euismod rhoncus nulla. Proin sed magna egestas, egestas ante et, congue eros. In consequat, mauris dapibus tincidunt suscipit, ex libero aliquet diam, at maximus risus enim non leo.
                    </p>
                </div>
            </div>
        </div>
    </div>

    <div id="experience" className="background-alt">
        <h2 className="heading">Experience</h2>
        <div className="container">
            <div className="row">
                <div className="experience shadow-large">
                    <div className="experience-image">
                        <Image alt="" width="100px" height="100px" src="data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAkGBxIQEhEQEBMWEBMPFhAVExISFxUWFxcXFhYWGBYWFxUYHSggGBolHRUVITEiMSotLi4uFyAzODMsNygtLisBCgoKDg0OGxAQGy4mICYtLS0tLy0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLf/AABEIAOEA4QMBIgACEQEDEQH/xAAcAAEAAgMBAQEAAAAAAAAAAAAABgcBBAUDAgj/xABOEAABAwIDBAUFCwYNBQEAAAABAAIDBBEFEiEGBzFBEyJRYXEXMoGR0hQ1QlJUcpKTobGzIzRiw9HTFSUzQ0RTc3SEosHC4WOCg7LwJP/EABoBAQADAQEBAAAAAAAAAAAAAAACAwQBBQb/xAA0EQACAgECAwUFBwUBAAAAAAAAAQIDEQQhBRIxEyJBUZFhcYHB8BQjMqGx0eEVJDNScgb/2gAMAwEAAhEDEQA/ALxREQBERAEREAREQBERAEREAREQBERAEREAREQBERAEREAREQBERAEREAREQBERAEREAREQBERAEREAREQBERAEREAREQBERAEREAREQBERAEREAREQBERAEREAREQBERAEREAREQBERAEREAREQBERAEREAREQBERAEREAREQBERAEREAREQBERAEREAREQBERAEREAREQBERAEREAREQBERAEREAREQGCovtxtG/D4o5GRtlL3ltnEi3Vc6+gPYpQVyMcwOGsEbZwXNieXhoJAJsRrbiNVGabXd6l2nlVG2LtWY53XmV0d684407B4uf7KeVefnTx/Tf7KsmkwOliAEdPEy3xY2/fbVUtvDYG4hUhoDQOj0AsP5NvJZbO1hHPMfR8Pjw/WXdmqMbZzzP9yQnezN8nj+m72V6U29Gd72M9zsGcsFw5+mZwF/N71Id2VFG/D4i+Njznm1c0H+cd2hdOv2OopiHdAyJ7S1wfCBGbtIIvl0PDmpqNrSfMZLr+HV2zqlRjDaypN7rxxlfqc3bnaybDnwhkTJWTB2rnFpBba40B0s4epRnyszj+jxn/AL3+ytvfT/RP8R/sWvudha51VnaH2bDbOAebr8fQozlPteVMv0+m0kOG/abK+Zp+bWd8efyPPysT8qdn0n+ypzsXtA6vpzO9gjIkezK0kjqgG9yO9blbglJN1ZYIXk9rG38QbXHivjDMGjoYZY6cENJkkDSS6zi0aC/LRXQjYn3pZR5mqv0dlWKquSWV4trHj1ODtTvChpXuhhYZ5WaO1ysaewu5nuCinlKrnklkUdv0Y5H/AOYPUKglHStfN125w6RvN3XBeNeZ1V44Ttdhz2Bsc0UIAsI32iI7spss8LJWN97B6+q0VGgrj9y7G1vJt4Xp+WSDU+9SqBtJDE+3HKHsP3lWHsjj4r4OnDDHZzmFpN9W21B7NV9VuG0Vc2z2RTg/CblLh3h7dQfSvPZ/B48OhlY15dGHSSgu4tBAuCedrFXxjOL3eUeTqrtHbV93VyTyvHKa+vYbmN45BRs6Sd4YOQ4ucexrRqSq+xLeu65FNAMo4Oldf/K3h61CdosZkrZ3zSE2JLWtPBjOQA+096sfd5sbEyKOrqGCSWUZmNeLhjT5vVOmY8b96q7SdkuWOyPTlw7S6DTq3VJyk+kei93w8SPHeVX2zdHFl7ejkt9LMpLsTtzLWz+55YmN6jn52E8iBax8e1Twxi1rC3ZYWXDh2ep4JzVxNEJyPa8MsGuBscxA4Hq8Rx5qxVzTT5snnWavR2Vyj2HLLHdabe/14m5jWNwUcfSTvyDgBxc49jW8SVXuJb1X3Ip4BlHB0pJP0W/tUN2qxt1dUPmceoHFsbeTWA6W7zxP/CsLdtsnG2FlXOwPkl60YeLhjeRAPwjxv3qvtZ2S5YbI9F8O02h06u1S5pPpHovrzZwfKXXt6zo4g3vje0evMu1g+9KNxDauIxX/AJyM52jvIOoHrVhzQNe0tc0OB4ggEeoqnN5OyzKN7JoBlhmJBYODH8er2NIvp3KU1ZWubmyV6OWg1s+xlVyN9GmXDSVTJWtfG4Pa8Xa5pBBHaCFsqm91OPujnFI43jnzFoPBsgF9OwOAPpCuMK6uxTjk8nX6OWkudTefFPzX11MoiKZjCIiAIiIAsWWUQGLKhd4/vhU/+L8MK+iqG3je+NT4x/htWbVfg+J7/wD5tf3b/wCX8iyt1vvfF8+b/wB3KX2UP3VH+Lovnz/iFTFXV/gXuR5evX91b/0/1Ku30/0T/EfcxRDZLZ6orTKKZ7YzGGF2Zz23zZreaDfgVL99B/NP8R/sXE3bbQ09C6c1Di3pBEG5Wud5pffgNOIWSzld3e6fwfT6Kd0OE81KzLLxtnx8vcSPYzY2ro6xs05ZIwRytzh7nG7sttHC/JWOVCajedQtHV6WQ9jWW+11gvrZjbF1cavLGImwRtcy5zOJOfzuXwRotEJVruxZ4Oro1t2b7oY6ZeOX2Lb+DlbVbthK981I5rS8lzon3Dcx1Ja4cL9ihdZsViEV7073gc2Frx6mm/2KY4FvRaQG1kRadLyxatPeWHUei6kke3uHOF/dLW9zg4H1EKrkps3TPShrOK6JKucOZLps3+a6lIAS079M8L2/PjePuKs3ZjaOWuoa6nkOeWGCTK8cXtcxwF/0gdPSuHvH2lpq0wtpwXGMuLpS0tuCLZRexI5+hdjdBhLwJ6l4IZK1sbL/AAgDdzvDUD0FV1Jxs5YvKNnEZxu0C1F0OWeVhePX1w14Mq53A+lfpHBZWvggczVro4yLdmUKmtutk5KKV0jGk07yS1wF8pOuR/ZzseC39htuvcjRT1AL4QSWOZq5l9cpHNv3LtMlVNxkOLVPiOnhfp98dUuu/X4ry9C5lpYswuhma3iYpQPEtNlwzt9h+XN7oHzcr830bXWlgO2gr6zoIWFsLY5HFzx1nEFoFh8Eanv8Fr7SPTJ8vHR6jDnyPEd3lY/UpS2vp/1X6L2Yka+kpnM80xRWt3NAVTbfbJvpZXTxtJgkcXXb8BxNy13YL6g+jRbWwe3Ao2+5qgExXJa5upZfiC3m2/ZwWOl9lNxkfUcVrfEtLC7T746pdd+vxXl8S5FAt8EjRRsafOdMzL6GvJ+xdKbeDh7WZhOH/osa4u9VtFVm2G0r8QlDsuSNl2xxg3Op1c63wjp/yr77YqDWTyeEcOvnqY2Si1GLy29un8njsPGXV1IG/wBcD6ACT9l1+hAq13YbKPhPu2oaWPcC2Fh4taeL3DkTwA7PFWUE08HGG/iR47qoajU9zdRWM+by8/sZREWg8UIiIAiIgCIvl5sL9iAyVEq/d/RTyPmk6UvkcXOPSOGp7uQUa2o3qZHuioWNkDCQZ5LlpI+I1pFx339Cj/lWxDsp/q3+2tK0Ns45x6lcOI9hJ8k2n7C3MAwKGijdFBmyOcXWe4usTa9ieHBdYlUaN6uI9kH1b/bVm7Iy4hKzpa/oo8wuyGNhDgDze4uNj3KNumnUu9j1OR1Suk3u34s9cf2Sp657Hz9ITGCGhry0AE3Og5nT1Ll+TLD+yX6w/sWNtdvY6A9DG0T1BAJZezWA8C89vdx8FAjvWxDk2nHd0b/bXIaGdq5lH1L/AOq2ULs42SSXgmyfeTLD+yX6w/sXVwHZOloel6AO/LBofncXXAvYa/OKqzyq4h2U/wBW721LdicbxTECJZOhhpwfP6J2Z9uIjBfbxdw8V2ehdS52kvicfFbb1yOcn7NzqVm7egkNwx8X9k8gfRNwFondVScp6gemL92pLtNtHDh8JlmNydI4x5z3djR954BVbU72K1ziY44I28mua959LswufQqqtC7lmMUXvjOoo27WXqTvDt3FDCQ5zXzEf1rrj6LQAfUpZFG1gDWgNA0AFgAO4Kk/KtiHZT/Vv9tdPZ3bbF6+UQwNp9LF7zG/LG34zjn9Q4n7Vo+wTrWdkveZLOJPUSXPJyftLalia4EOAcDxBAIPoUVxLd5QTkuyOiJ49C7KL/NNx9ikJn6CEyVEjfybSZJCMje82ubD0qrcc3syl5bRRMawHR8wc5zu/ICMo8bnwVENNK94SyWR1ktM+aMnF+w73kqpb/y09vGL92u5s7sZTUT+li6R0haW5pHX0Nr6AAcuxVl5VsR7Kf6t/tr1p952JyvbHGyF75CGsY2J5LieQ66tXDJx3wvU7Zxy66PJOyTT8PMumSMOBDgCDoQbEHxCiuJbu6CYlwY6EniYXBo+iQR9i6+z7avo71z4zK63UhaWtZ3Zi45j36KH7YbzG0z3QUjGzyMNnyOJ6NrvigDVxHPUBUqh2y5Us/oIauen78ZOPu2Nhu6ykB1lqCOy8X+jF3cH2MoqUhzIszxwfIc7h4E8FWHlWxDsp/q3/vEO9bEOyn+rf+8V8eFzjuoo5bxy21cs7JNeReAC+lDNiK3EqprZ6zooYni7I2xuEjxycSX9Qei5UyCzyjyvGfQhGXMsmURFwkEREAREQGCuDtTgLq6PofdElPGfPbEG3f3OcRfL3Diu8VGNutqXYZFFKIhN0snR5S/Jbqude+U381TrUnJKPXwIzcVFuXQjfkfp/lU30Y/ZTyP0/wAqm+jH7K5/lhf8jH15/dLcwze7E5wbUwOhbcXex4kDR2ublabeF1tf2xb5f5GRPTPbH5M7+zm72koniUZp5G+a6XKQ09rWgAA9/FSXEad8kbmRymBztBI0Bxb4B2l17U8zZGtewhzXAFrhqCDqCD2L1WGU5SeZPLNcYRisRWxWsm6OFxLnVc7nOJLnOEZJJ4kkjUrHkfg+VTeqP2VZd1lXfarv9iv7PV/qV7h+6ejjcHSySzga5HFrWnudlAJHddTyKEMaGMAa1os0AWAA4AAcl7LF1VZZOzeTyTjCMfwogWM7txWSmaorZ3uOgGWMNa34rG5eqP8A43Wj5H6f5VN6o/ZVmLhbZ4y6hpJKljRI6PIMriQDme1vEeKthfdtGMiudNe8miJxboKYEZqmdw5gdGL918qm2B4LBRRiGnYGNGp5ucfjOcdXHvWnsXjTq+kjqXsEbnmQZWkkDI9zRqfmrvqNttsnyzb2JVwglmKIptXsicRIElVLFE2xEMYZlJ+M64u49nIKPeR+D5VN9GP2VZiLkL7ILEXhHZUwk8yRWg3P0/yqb1R+ypNszsXS4f1oWl8pFjNJZz7cwLABo8ApKiTvsmsSkI01xeUjk7QYW+qiMTJ30wdo58QbnI+KHHzfEaqE+R6n+VTeqP2VZiJXdOv8LwJ1Qm8yRWnkep/lM3qj9ldLBN2NHTPEry+pcwgtEuXICOByNADj43U5RSlqbZLDkziorTykYssoioLQiIgCIiAIiIAq233/AJrTf2/6qRWSq333fmtN/eP1civ0v+aPvKdT/il7iU7EtH8HUOg/Nqfl/wBNq4O9vDoXUL5y1olhdF0bwAHdaRrS2/MEE6dyimC1W0Ap4BTRkwCOPoSG0x/J5Rk8434W46rj7VS4o7o3YoyboWuHVAjYzs0dGC0OIuATfitFWnatUuZdfB7lFly7PHK+nkWdupe44bBm+C6YNv8AFEjrej9i3dptsqTD7NmcXSEXEUYzPI7TwDR4kL02LxGmqKSM0gyRxgR9GfOYWjzXd/O/O91wotgadlXNW1cvuhjznayfKA1xJuXng8AZQ0WFhe99FnfI7JOe3Xb5Fy5lCKh6mrTb3qNzgHQzsHxvybreIDr/AHqdYZiUVTG2aB4kY/g5vdxBHEEdij+LfwRURuhkfS2IsC18TXNPa1wOhCiG5mocyprKYOzxhuYEcCWPyZx85pb6gpOuEoOUE015kVZKM1GTTyTXFtsoKarioXslMk/Q5XNDSwdK4tbclwPEG+i5uO7zaKleYm56hzSQ4xZcoI4jM4i58LqF72s/8Jx9HcSGKnDCDY5i+QNseWpCsfZnY2lo4Ws6JkkhaOkke0OLjz48G9gUpVVQhGUsvK6BTsnOUY+D6nlsvt7S17ujZnil1IjlABcBxLS0kHw49y896/vZUeMP4rFA9ucNjw/FKSSlHRCQwyZG6AO6XK7KOQItp3ntU83re9lR4w/isXezjGyuUOjx+pznk4TUuq/Y+d0p/iyD51R+M9fe0G3tNRzimLZZ5Ta7IGtdZx81hzOHWPZ9yg2G7Y+4MJgggINVKajKOPRtMz+uRzPxRzNuXGSbudijB/8AtrAXVMly1rjcx5uLiechubnle3au2VRUpTs6ZeF5/wAHITbjGEPJZJ9TyFzWuLSwuAJa61xpwNiRf0r2WAFlYjWEREAREQBERAEREAREQBERAEREAVb77vzWm/t/1UiscqA73sNnqaenZTxPmc2bMRGLkDo3i57rkK/TNK6LfmU6hZrkl5Ei2I97qD+7U/4bVu4zDG+CdswBjMcmfNwy5Te/3qqsNxfHaeKKCOkdkhYxjLwOJytAAuc2psF8VzMexIdBLE6KN1g8ZWwsI/TJOYjuHqKsem72XKKXvIdt3cKL9Da3HSOBrQScgZTuPzvymvjYfYubhdLNtFVzOmlcyCGzgxuoa1znCNrGnTMcpJcQeHhaytitmG4dTmK/SSSHNM/gHG1rC/wQNB6VXz8ExHBamSaiiNRBJcWY0yXZe4a9jes0tvoQrlbGdk3HZv8AC39dWVODjCKluvHBJxusw5rbuMptqSZLeN7BRvc3l93VfR6s6J+Qnjl6VuX7LLblqsaxYe5zB7hgfpK9zHxkt5jr9Zw7gNe1bO7bZ2eixCsD4nthayRkUrhYPAlGUg8CS0ArjnLspqyeX5Zz4nVFdpFwjhefwOft4L49Qg8L0H47lb4VXbY4RUyY1STxwSPijNFmka27RllcXXPKwN1aIWe9pxrx5fNl1McSn7yot73vhQfNi/HUu3re9lR4w/isUd3nYPUz11HJDDJKyNsedzGkhtprm58NVJ95FHJPh88ULHSvcYrMYLk2kYTYeAVnMvufZ19SDT+826/sVTHs5I2gp8Vpic8TpDKBqW9HK4NlAN9AALjuv2q29h9qGYhDn0bNHZs0Y5Hk4fonl6RyXhu3oZIsPiinjdG8GfNHILGzpXkXHeD9qh+L7M1WF1zavC4nSxPJvEwXygm74nD4h+CeRHcFKycbpShJ7pvD+RGEXUlJLZ9V8y3LrK08OqjLGyQsdEXgEskBa5p5ggrcWE2BERAEREAREQBERAEREAREQBERAEREAREQBERAEREAREQBERAEREAREQBERAEREAREQBERAEREAREQBERAEREAREQBERAEREAREQBERAEREAREQBERAEREAREQBERAEREAREQBERAEREAREQBERAEREAREQBERAEREAREQBERAEREAREQBERAEREAREQBERAEREAREQBERAEREAREQBERAEREAREQBERAEREAREQBERAEREAREQBERAEREAREQBERAEREAREQBERAEREAREQBERAEREAREQBERAEREAREQH//Z" />
                    </div>
                    <div className="experience-info">
                        <h3>Lead Cloud Engineer</h3>
                        January 2022 - Present<br /><br />
                        <p>
                            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur in iaculis ex. Etiam volutpat laoreet urna. Morbi ut tortor nec nulla commodo malesuada sit amet vel lacus. Fusce eget efficitur libero. Morbi dapibus porta quam laoreet placerat.
                        </p>

                    </div>
                </div>

                <div className="experience shadow-large">
                    <div className="experience-image">
                        <Image alt="" width="100px" height="100px" src="data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAkGBxIQEhEQEBMWEBMPFhAVExISFxUWFxcXFhYWGBYWFxUYHSggGBolHRUVITEiMSotLi4uFyAzODMsNygtLisBCgoKDg0OGxAQGy4mICYtLS0tLy0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLf/AABEIAOEA4QMBIgACEQEDEQH/xAAcAAEAAgMBAQEAAAAAAAAAAAAABgcBBAUDAgj/xABOEAABAwIDBAUFCwYNBQEAAAABAAIDBBEFEiEGBzFBEyJRYXEXMoGR0hQ1QlJUcpKTobGzIzRiw9HTFSUzQ0RTc3SEosHC4WOCg7LwJP/EABoBAQADAQEBAAAAAAAAAAAAAAACAwQBBQb/xAA0EQACAgECAwUFBwUBAAAAAAAAAQIDEQQhBRIxEyJBUZFhcYHB8BQjMqGx0eEVJDNScgb/2gAMAwEAAhEDEQA/ALxREQBERAEREAREQBERAEREAREQBERAEREAREQBERAEREAREQBERAEREAREQBERAEREAREQBERAEREAREQBERAEREAREQBERAEREAREQBERAEREAREQBERAEREAREQBERAEREAREQBERAEREAREQBERAEREAREQBERAEREAREQBERAEREAREQBERAEREAREQBERAEREAREQBERAEREAREQBERAEREAREQGCovtxtG/D4o5GRtlL3ltnEi3Vc6+gPYpQVyMcwOGsEbZwXNieXhoJAJsRrbiNVGabXd6l2nlVG2LtWY53XmV0d684407B4uf7KeVefnTx/Tf7KsmkwOliAEdPEy3xY2/fbVUtvDYG4hUhoDQOj0AsP5NvJZbO1hHPMfR8Pjw/WXdmqMbZzzP9yQnezN8nj+m72V6U29Gd72M9zsGcsFw5+mZwF/N71Id2VFG/D4i+Njznm1c0H+cd2hdOv2OopiHdAyJ7S1wfCBGbtIIvl0PDmpqNrSfMZLr+HV2zqlRjDaypN7rxxlfqc3bnaybDnwhkTJWTB2rnFpBba40B0s4epRnyszj+jxn/AL3+ytvfT/RP8R/sWvudha51VnaH2bDbOAebr8fQozlPteVMv0+m0kOG/abK+Zp+bWd8efyPPysT8qdn0n+ypzsXtA6vpzO9gjIkezK0kjqgG9yO9blbglJN1ZYIXk9rG38QbXHivjDMGjoYZY6cENJkkDSS6zi0aC/LRXQjYn3pZR5mqv0dlWKquSWV4trHj1ODtTvChpXuhhYZ5WaO1ysaewu5nuCinlKrnklkUdv0Y5H/AOYPUKglHStfN125w6RvN3XBeNeZ1V44Ttdhz2Bsc0UIAsI32iI7spss8LJWN97B6+q0VGgrj9y7G1vJt4Xp+WSDU+9SqBtJDE+3HKHsP3lWHsjj4r4OnDDHZzmFpN9W21B7NV9VuG0Vc2z2RTg/CblLh3h7dQfSvPZ/B48OhlY15dGHSSgu4tBAuCedrFXxjOL3eUeTqrtHbV93VyTyvHKa+vYbmN45BRs6Sd4YOQ4ucexrRqSq+xLeu65FNAMo4Oldf/K3h61CdosZkrZ3zSE2JLWtPBjOQA+096sfd5sbEyKOrqGCSWUZmNeLhjT5vVOmY8b96q7SdkuWOyPTlw7S6DTq3VJyk+kei93w8SPHeVX2zdHFl7ejkt9LMpLsTtzLWz+55YmN6jn52E8iBax8e1Twxi1rC3ZYWXDh2ep4JzVxNEJyPa8MsGuBscxA4Hq8Rx5qxVzTT5snnWavR2Vyj2HLLHdabe/14m5jWNwUcfSTvyDgBxc49jW8SVXuJb1X3Ip4BlHB0pJP0W/tUN2qxt1dUPmceoHFsbeTWA6W7zxP/CsLdtsnG2FlXOwPkl60YeLhjeRAPwjxv3qvtZ2S5YbI9F8O02h06u1S5pPpHovrzZwfKXXt6zo4g3vje0evMu1g+9KNxDauIxX/AJyM52jvIOoHrVhzQNe0tc0OB4ggEeoqnN5OyzKN7JoBlhmJBYODH8er2NIvp3KU1ZWubmyV6OWg1s+xlVyN9GmXDSVTJWtfG4Pa8Xa5pBBHaCFsqm91OPujnFI43jnzFoPBsgF9OwOAPpCuMK6uxTjk8nX6OWkudTefFPzX11MoiKZjCIiAIiIAsWWUQGLKhd4/vhU/+L8MK+iqG3je+NT4x/htWbVfg+J7/wD5tf3b/wCX8iyt1vvfF8+b/wB3KX2UP3VH+Lovnz/iFTFXV/gXuR5evX91b/0/1Ku30/0T/EfcxRDZLZ6orTKKZ7YzGGF2Zz23zZreaDfgVL99B/NP8R/sXE3bbQ09C6c1Di3pBEG5Wud5pffgNOIWSzld3e6fwfT6Kd0OE81KzLLxtnx8vcSPYzY2ro6xs05ZIwRytzh7nG7sttHC/JWOVCajedQtHV6WQ9jWW+11gvrZjbF1cavLGImwRtcy5zOJOfzuXwRotEJVruxZ4Oro1t2b7oY6ZeOX2Lb+DlbVbthK981I5rS8lzon3Dcx1Ja4cL9ihdZsViEV7073gc2Frx6mm/2KY4FvRaQG1kRadLyxatPeWHUei6kke3uHOF/dLW9zg4H1EKrkps3TPShrOK6JKucOZLps3+a6lIAS079M8L2/PjePuKs3ZjaOWuoa6nkOeWGCTK8cXtcxwF/0gdPSuHvH2lpq0wtpwXGMuLpS0tuCLZRexI5+hdjdBhLwJ6l4IZK1sbL/AAgDdzvDUD0FV1Jxs5YvKNnEZxu0C1F0OWeVhePX1w14Mq53A+lfpHBZWvggczVro4yLdmUKmtutk5KKV0jGk07yS1wF8pOuR/ZzseC39htuvcjRT1AL4QSWOZq5l9cpHNv3LtMlVNxkOLVPiOnhfp98dUuu/X4ry9C5lpYswuhma3iYpQPEtNlwzt9h+XN7oHzcr830bXWlgO2gr6zoIWFsLY5HFzx1nEFoFh8Eanv8Fr7SPTJ8vHR6jDnyPEd3lY/UpS2vp/1X6L2Yka+kpnM80xRWt3NAVTbfbJvpZXTxtJgkcXXb8BxNy13YL6g+jRbWwe3Ao2+5qgExXJa5upZfiC3m2/ZwWOl9lNxkfUcVrfEtLC7T746pdd+vxXl8S5FAt8EjRRsafOdMzL6GvJ+xdKbeDh7WZhOH/osa4u9VtFVm2G0r8QlDsuSNl2xxg3Op1c63wjp/yr77YqDWTyeEcOvnqY2Si1GLy29un8njsPGXV1IG/wBcD6ACT9l1+hAq13YbKPhPu2oaWPcC2Fh4taeL3DkTwA7PFWUE08HGG/iR47qoajU9zdRWM+by8/sZREWg8UIiIAiIgCIvl5sL9iAyVEq/d/RTyPmk6UvkcXOPSOGp7uQUa2o3qZHuioWNkDCQZ5LlpI+I1pFx339Cj/lWxDsp/q3+2tK0Ns45x6lcOI9hJ8k2n7C3MAwKGijdFBmyOcXWe4usTa9ieHBdYlUaN6uI9kH1b/bVm7Iy4hKzpa/oo8wuyGNhDgDze4uNj3KNumnUu9j1OR1Suk3u34s9cf2Sp657Hz9ITGCGhry0AE3Og5nT1Ll+TLD+yX6w/sWNtdvY6A9DG0T1BAJZezWA8C89vdx8FAjvWxDk2nHd0b/bXIaGdq5lH1L/AOq2ULs42SSXgmyfeTLD+yX6w/sXVwHZOloel6AO/LBofncXXAvYa/OKqzyq4h2U/wBW721LdicbxTECJZOhhpwfP6J2Z9uIjBfbxdw8V2ehdS52kvicfFbb1yOcn7NzqVm7egkNwx8X9k8gfRNwFondVScp6gemL92pLtNtHDh8JlmNydI4x5z3djR954BVbU72K1ziY44I28mua959LswufQqqtC7lmMUXvjOoo27WXqTvDt3FDCQ5zXzEf1rrj6LQAfUpZFG1gDWgNA0AFgAO4Kk/KtiHZT/Vv9tdPZ3bbF6+UQwNp9LF7zG/LG34zjn9Q4n7Vo+wTrWdkveZLOJPUSXPJyftLalia4EOAcDxBAIPoUVxLd5QTkuyOiJ49C7KL/NNx9ikJn6CEyVEjfybSZJCMje82ubD0qrcc3syl5bRRMawHR8wc5zu/ICMo8bnwVENNK94SyWR1ktM+aMnF+w73kqpb/y09vGL92u5s7sZTUT+li6R0haW5pHX0Nr6AAcuxVl5VsR7Kf6t/tr1p952JyvbHGyF75CGsY2J5LieQ66tXDJx3wvU7Zxy66PJOyTT8PMumSMOBDgCDoQbEHxCiuJbu6CYlwY6EniYXBo+iQR9i6+z7avo71z4zK63UhaWtZ3Zi45j36KH7YbzG0z3QUjGzyMNnyOJ6NrvigDVxHPUBUqh2y5Us/oIauen78ZOPu2Nhu6ykB1lqCOy8X+jF3cH2MoqUhzIszxwfIc7h4E8FWHlWxDsp/q3/vEO9bEOyn+rf+8V8eFzjuoo5bxy21cs7JNeReAC+lDNiK3EqprZ6zooYni7I2xuEjxycSX9Qei5UyCzyjyvGfQhGXMsmURFwkEREAREQGCuDtTgLq6PofdElPGfPbEG3f3OcRfL3Diu8VGNutqXYZFFKIhN0snR5S/Jbqude+U381TrUnJKPXwIzcVFuXQjfkfp/lU30Y/ZTyP0/wAqm+jH7K5/lhf8jH15/dLcwze7E5wbUwOhbcXex4kDR2ublabeF1tf2xb5f5GRPTPbH5M7+zm72koniUZp5G+a6XKQ09rWgAA9/FSXEad8kbmRymBztBI0Bxb4B2l17U8zZGtewhzXAFrhqCDqCD2L1WGU5SeZPLNcYRisRWxWsm6OFxLnVc7nOJLnOEZJJ4kkjUrHkfg+VTeqP2VZd1lXfarv9iv7PV/qV7h+6ejjcHSySzga5HFrWnudlAJHddTyKEMaGMAa1os0AWAA4AAcl7LF1VZZOzeTyTjCMfwogWM7txWSmaorZ3uOgGWMNa34rG5eqP8A43Wj5H6f5VN6o/ZVmLhbZ4y6hpJKljRI6PIMriQDme1vEeKthfdtGMiudNe8miJxboKYEZqmdw5gdGL918qm2B4LBRRiGnYGNGp5ucfjOcdXHvWnsXjTq+kjqXsEbnmQZWkkDI9zRqfmrvqNttsnyzb2JVwglmKIptXsicRIElVLFE2xEMYZlJ+M64u49nIKPeR+D5VN9GP2VZiLkL7ILEXhHZUwk8yRWg3P0/yqb1R+ypNszsXS4f1oWl8pFjNJZz7cwLABo8ApKiTvsmsSkI01xeUjk7QYW+qiMTJ30wdo58QbnI+KHHzfEaqE+R6n+VTeqP2VZiJXdOv8LwJ1Qm8yRWnkep/lM3qj9ldLBN2NHTPEry+pcwgtEuXICOByNADj43U5RSlqbZLDkziorTykYssoioLQiIgCIiAIiIAq233/AJrTf2/6qRWSq333fmtN/eP1civ0v+aPvKdT/il7iU7EtH8HUOg/Nqfl/wBNq4O9vDoXUL5y1olhdF0bwAHdaRrS2/MEE6dyimC1W0Ap4BTRkwCOPoSG0x/J5Rk8434W46rj7VS4o7o3YoyboWuHVAjYzs0dGC0OIuATfitFWnatUuZdfB7lFly7PHK+nkWdupe44bBm+C6YNv8AFEjrej9i3dptsqTD7NmcXSEXEUYzPI7TwDR4kL02LxGmqKSM0gyRxgR9GfOYWjzXd/O/O91wotgadlXNW1cvuhjznayfKA1xJuXng8AZQ0WFhe99FnfI7JOe3Xb5Fy5lCKh6mrTb3qNzgHQzsHxvybreIDr/AHqdYZiUVTG2aB4kY/g5vdxBHEEdij+LfwRURuhkfS2IsC18TXNPa1wOhCiG5mocyprKYOzxhuYEcCWPyZx85pb6gpOuEoOUE015kVZKM1GTTyTXFtsoKarioXslMk/Q5XNDSwdK4tbclwPEG+i5uO7zaKleYm56hzSQ4xZcoI4jM4i58LqF72s/8Jx9HcSGKnDCDY5i+QNseWpCsfZnY2lo4Ws6JkkhaOkke0OLjz48G9gUpVVQhGUsvK6BTsnOUY+D6nlsvt7S17ujZnil1IjlABcBxLS0kHw49y896/vZUeMP4rFA9ucNjw/FKSSlHRCQwyZG6AO6XK7KOQItp3ntU83re9lR4w/isXezjGyuUOjx+pznk4TUuq/Y+d0p/iyD51R+M9fe0G3tNRzimLZZ5Ta7IGtdZx81hzOHWPZ9yg2G7Y+4MJgggINVKajKOPRtMz+uRzPxRzNuXGSbudijB/8AtrAXVMly1rjcx5uLiechubnle3au2VRUpTs6ZeF5/wAHITbjGEPJZJ9TyFzWuLSwuAJa61xpwNiRf0r2WAFlYjWEREAREQBERAEREAREQBERAEREAVb77vzWm/t/1UiscqA73sNnqaenZTxPmc2bMRGLkDo3i57rkK/TNK6LfmU6hZrkl5Ei2I97qD+7U/4bVu4zDG+CdswBjMcmfNwy5Te/3qqsNxfHaeKKCOkdkhYxjLwOJytAAuc2psF8VzMexIdBLE6KN1g8ZWwsI/TJOYjuHqKsem72XKKXvIdt3cKL9Da3HSOBrQScgZTuPzvymvjYfYubhdLNtFVzOmlcyCGzgxuoa1znCNrGnTMcpJcQeHhaytitmG4dTmK/SSSHNM/gHG1rC/wQNB6VXz8ExHBamSaiiNRBJcWY0yXZe4a9jes0tvoQrlbGdk3HZv8AC39dWVODjCKluvHBJxusw5rbuMptqSZLeN7BRvc3l93VfR6s6J+Qnjl6VuX7LLblqsaxYe5zB7hgfpK9zHxkt5jr9Zw7gNe1bO7bZ2eixCsD4nthayRkUrhYPAlGUg8CS0ArjnLspqyeX5Zz4nVFdpFwjhefwOft4L49Qg8L0H47lb4VXbY4RUyY1STxwSPijNFmka27RllcXXPKwN1aIWe9pxrx5fNl1McSn7yot73vhQfNi/HUu3re9lR4w/isUd3nYPUz11HJDDJKyNsedzGkhtprm58NVJ95FHJPh88ULHSvcYrMYLk2kYTYeAVnMvufZ19SDT+826/sVTHs5I2gp8Vpic8TpDKBqW9HK4NlAN9AALjuv2q29h9qGYhDn0bNHZs0Y5Hk4fonl6RyXhu3oZIsPiinjdG8GfNHILGzpXkXHeD9qh+L7M1WF1zavC4nSxPJvEwXygm74nD4h+CeRHcFKycbpShJ7pvD+RGEXUlJLZ9V8y3LrK08OqjLGyQsdEXgEskBa5p5ggrcWE2BERAEREAREQBERAEREAREQBERAEREAREQBERAEREAREQBERAEREAREQBERAEREAREQBERAEREAREQBERAEREAREQBERAEREAREQBERAEREAREQBERAEREAREQBERAEREAREQBERAEREAREQBERAEREAREQBERAEREAREQBERAEREAREQBERAEREAREQBERAEREAREQBERAEREAREQBERAEREAREQBERAEREAREQBERAEREAREQBERAEREAREQBERAEREAREQBERAEREAREQBERAEREAREQBERAEREAREQH//Z" />
                    </div>
                    <div className="experience-info">
                        <h3>Senior Cloud Engineer</h3>
                        September 2018 - January 2022<br /><br />
                        <p>
                            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur in iaculis ex. Etiam volutpat laoreet urna. Morbi ut tortor nec nulla commodo malesuada sit amet vel lacus. Fusce eget efficitur libero. Morbi dapibus porta quam laoreet placerat.
                        </p>

                    </div>
                </div>

                <div className="experience shadow-large">
                    <div className="experience-image">
                        <Image alt="" width="100px" height="100px" src="data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAkGBxIQEhEQEBMWEBMPFhAVExISFxUWFxcXFhYWGBYWFxUYHSggGBolHRUVITEiMSotLi4uFyAzODMsNygtLisBCgoKDg0OGxAQGy4mICYtLS0tLy0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLf/AABEIAOEA4QMBIgACEQEDEQH/xAAcAAEAAgMBAQEAAAAAAAAAAAAABgcBBAUDAgj/xABOEAABAwIDBAUFCwYNBQEAAAABAAIDBBEFEiEGBzFBEyJRYXEXMoGR0hQ1QlJUcpKTobGzIzRiw9HTFSUzQ0RTc3SEosHC4WOCg7LwJP/EABoBAQADAQEBAAAAAAAAAAAAAAACAwQBBQb/xAA0EQACAgECAwUFBwUBAAAAAAAAAQIDEQQhBRIxEyJBUZFhcYHB8BQjMqGx0eEVJDNScgb/2gAMAwEAAhEDEQA/ALxREQBERAEREAREQBERAEREAREQBERAEREAREQBERAEREAREQBERAEREAREQBERAEREAREQBERAEREAREQBERAEREAREQBERAEREAREQBERAEREAREQBERAEREAREQBERAEREAREQBERAEREAREQBERAEREAREQBERAEREAREQBERAEREAREQBERAEREAREQBERAEREAREQBERAEREAREQBERAEREAREQGCovtxtG/D4o5GRtlL3ltnEi3Vc6+gPYpQVyMcwOGsEbZwXNieXhoJAJsRrbiNVGabXd6l2nlVG2LtWY53XmV0d684407B4uf7KeVefnTx/Tf7KsmkwOliAEdPEy3xY2/fbVUtvDYG4hUhoDQOj0AsP5NvJZbO1hHPMfR8Pjw/WXdmqMbZzzP9yQnezN8nj+m72V6U29Gd72M9zsGcsFw5+mZwF/N71Id2VFG/D4i+Njznm1c0H+cd2hdOv2OopiHdAyJ7S1wfCBGbtIIvl0PDmpqNrSfMZLr+HV2zqlRjDaypN7rxxlfqc3bnaybDnwhkTJWTB2rnFpBba40B0s4epRnyszj+jxn/AL3+ytvfT/RP8R/sWvudha51VnaH2bDbOAebr8fQozlPteVMv0+m0kOG/abK+Zp+bWd8efyPPysT8qdn0n+ypzsXtA6vpzO9gjIkezK0kjqgG9yO9blbglJN1ZYIXk9rG38QbXHivjDMGjoYZY6cENJkkDSS6zi0aC/LRXQjYn3pZR5mqv0dlWKquSWV4trHj1ODtTvChpXuhhYZ5WaO1ysaewu5nuCinlKrnklkUdv0Y5H/AOYPUKglHStfN125w6RvN3XBeNeZ1V44Ttdhz2Bsc0UIAsI32iI7spss8LJWN97B6+q0VGgrj9y7G1vJt4Xp+WSDU+9SqBtJDE+3HKHsP3lWHsjj4r4OnDDHZzmFpN9W21B7NV9VuG0Vc2z2RTg/CblLh3h7dQfSvPZ/B48OhlY15dGHSSgu4tBAuCedrFXxjOL3eUeTqrtHbV93VyTyvHKa+vYbmN45BRs6Sd4YOQ4ucexrRqSq+xLeu65FNAMo4Oldf/K3h61CdosZkrZ3zSE2JLWtPBjOQA+096sfd5sbEyKOrqGCSWUZmNeLhjT5vVOmY8b96q7SdkuWOyPTlw7S6DTq3VJyk+kei93w8SPHeVX2zdHFl7ejkt9LMpLsTtzLWz+55YmN6jn52E8iBax8e1Twxi1rC3ZYWXDh2ep4JzVxNEJyPa8MsGuBscxA4Hq8Rx5qxVzTT5snnWavR2Vyj2HLLHdabe/14m5jWNwUcfSTvyDgBxc49jW8SVXuJb1X3Ip4BlHB0pJP0W/tUN2qxt1dUPmceoHFsbeTWA6W7zxP/CsLdtsnG2FlXOwPkl60YeLhjeRAPwjxv3qvtZ2S5YbI9F8O02h06u1S5pPpHovrzZwfKXXt6zo4g3vje0evMu1g+9KNxDauIxX/AJyM52jvIOoHrVhzQNe0tc0OB4ggEeoqnN5OyzKN7JoBlhmJBYODH8er2NIvp3KU1ZWubmyV6OWg1s+xlVyN9GmXDSVTJWtfG4Pa8Xa5pBBHaCFsqm91OPujnFI43jnzFoPBsgF9OwOAPpCuMK6uxTjk8nX6OWkudTefFPzX11MoiKZjCIiAIiIAsWWUQGLKhd4/vhU/+L8MK+iqG3je+NT4x/htWbVfg+J7/wD5tf3b/wCX8iyt1vvfF8+b/wB3KX2UP3VH+Lovnz/iFTFXV/gXuR5evX91b/0/1Ku30/0T/EfcxRDZLZ6orTKKZ7YzGGF2Zz23zZreaDfgVL99B/NP8R/sXE3bbQ09C6c1Di3pBEG5Wud5pffgNOIWSzld3e6fwfT6Kd0OE81KzLLxtnx8vcSPYzY2ro6xs05ZIwRytzh7nG7sttHC/JWOVCajedQtHV6WQ9jWW+11gvrZjbF1cavLGImwRtcy5zOJOfzuXwRotEJVruxZ4Oro1t2b7oY6ZeOX2Lb+DlbVbthK981I5rS8lzon3Dcx1Ja4cL9ihdZsViEV7073gc2Frx6mm/2KY4FvRaQG1kRadLyxatPeWHUei6kke3uHOF/dLW9zg4H1EKrkps3TPShrOK6JKucOZLps3+a6lIAS079M8L2/PjePuKs3ZjaOWuoa6nkOeWGCTK8cXtcxwF/0gdPSuHvH2lpq0wtpwXGMuLpS0tuCLZRexI5+hdjdBhLwJ6l4IZK1sbL/AAgDdzvDUD0FV1Jxs5YvKNnEZxu0C1F0OWeVhePX1w14Mq53A+lfpHBZWvggczVro4yLdmUKmtutk5KKV0jGk07yS1wF8pOuR/ZzseC39htuvcjRT1AL4QSWOZq5l9cpHNv3LtMlVNxkOLVPiOnhfp98dUuu/X4ry9C5lpYswuhma3iYpQPEtNlwzt9h+XN7oHzcr830bXWlgO2gr6zoIWFsLY5HFzx1nEFoFh8Eanv8Fr7SPTJ8vHR6jDnyPEd3lY/UpS2vp/1X6L2Yka+kpnM80xRWt3NAVTbfbJvpZXTxtJgkcXXb8BxNy13YL6g+jRbWwe3Ao2+5qgExXJa5upZfiC3m2/ZwWOl9lNxkfUcVrfEtLC7T746pdd+vxXl8S5FAt8EjRRsafOdMzL6GvJ+xdKbeDh7WZhOH/osa4u9VtFVm2G0r8QlDsuSNl2xxg3Op1c63wjp/yr77YqDWTyeEcOvnqY2Si1GLy29un8njsPGXV1IG/wBcD6ACT9l1+hAq13YbKPhPu2oaWPcC2Fh4taeL3DkTwA7PFWUE08HGG/iR47qoajU9zdRWM+by8/sZREWg8UIiIAiIgCIvl5sL9iAyVEq/d/RTyPmk6UvkcXOPSOGp7uQUa2o3qZHuioWNkDCQZ5LlpI+I1pFx339Cj/lWxDsp/q3+2tK0Ns45x6lcOI9hJ8k2n7C3MAwKGijdFBmyOcXWe4usTa9ieHBdYlUaN6uI9kH1b/bVm7Iy4hKzpa/oo8wuyGNhDgDze4uNj3KNumnUu9j1OR1Suk3u34s9cf2Sp657Hz9ITGCGhry0AE3Og5nT1Ll+TLD+yX6w/sWNtdvY6A9DG0T1BAJZezWA8C89vdx8FAjvWxDk2nHd0b/bXIaGdq5lH1L/AOq2ULs42SSXgmyfeTLD+yX6w/sXVwHZOloel6AO/LBofncXXAvYa/OKqzyq4h2U/wBW721LdicbxTECJZOhhpwfP6J2Z9uIjBfbxdw8V2ehdS52kvicfFbb1yOcn7NzqVm7egkNwx8X9k8gfRNwFondVScp6gemL92pLtNtHDh8JlmNydI4x5z3djR954BVbU72K1ziY44I28mua959LswufQqqtC7lmMUXvjOoo27WXqTvDt3FDCQ5zXzEf1rrj6LQAfUpZFG1gDWgNA0AFgAO4Kk/KtiHZT/Vv9tdPZ3bbF6+UQwNp9LF7zG/LG34zjn9Q4n7Vo+wTrWdkveZLOJPUSXPJyftLalia4EOAcDxBAIPoUVxLd5QTkuyOiJ49C7KL/NNx9ikJn6CEyVEjfybSZJCMje82ubD0qrcc3syl5bRRMawHR8wc5zu/ICMo8bnwVENNK94SyWR1ktM+aMnF+w73kqpb/y09vGL92u5s7sZTUT+li6R0haW5pHX0Nr6AAcuxVl5VsR7Kf6t/tr1p952JyvbHGyF75CGsY2J5LieQ66tXDJx3wvU7Zxy66PJOyTT8PMumSMOBDgCDoQbEHxCiuJbu6CYlwY6EniYXBo+iQR9i6+z7avo71z4zK63UhaWtZ3Zi45j36KH7YbzG0z3QUjGzyMNnyOJ6NrvigDVxHPUBUqh2y5Us/oIauen78ZOPu2Nhu6ykB1lqCOy8X+jF3cH2MoqUhzIszxwfIc7h4E8FWHlWxDsp/q3/vEO9bEOyn+rf+8V8eFzjuoo5bxy21cs7JNeReAC+lDNiK3EqprZ6zooYni7I2xuEjxycSX9Qei5UyCzyjyvGfQhGXMsmURFwkEREAREQGCuDtTgLq6PofdElPGfPbEG3f3OcRfL3Diu8VGNutqXYZFFKIhN0snR5S/Jbqude+U381TrUnJKPXwIzcVFuXQjfkfp/lU30Y/ZTyP0/wAqm+jH7K5/lhf8jH15/dLcwze7E5wbUwOhbcXex4kDR2ublabeF1tf2xb5f5GRPTPbH5M7+zm72koniUZp5G+a6XKQ09rWgAA9/FSXEad8kbmRymBztBI0Bxb4B2l17U8zZGtewhzXAFrhqCDqCD2L1WGU5SeZPLNcYRisRWxWsm6OFxLnVc7nOJLnOEZJJ4kkjUrHkfg+VTeqP2VZd1lXfarv9iv7PV/qV7h+6ejjcHSySzga5HFrWnudlAJHddTyKEMaGMAa1os0AWAA4AAcl7LF1VZZOzeTyTjCMfwogWM7txWSmaorZ3uOgGWMNa34rG5eqP8A43Wj5H6f5VN6o/ZVmLhbZ4y6hpJKljRI6PIMriQDme1vEeKthfdtGMiudNe8miJxboKYEZqmdw5gdGL918qm2B4LBRRiGnYGNGp5ucfjOcdXHvWnsXjTq+kjqXsEbnmQZWkkDI9zRqfmrvqNttsnyzb2JVwglmKIptXsicRIElVLFE2xEMYZlJ+M64u49nIKPeR+D5VN9GP2VZiLkL7ILEXhHZUwk8yRWg3P0/yqb1R+ypNszsXS4f1oWl8pFjNJZz7cwLABo8ApKiTvsmsSkI01xeUjk7QYW+qiMTJ30wdo58QbnI+KHHzfEaqE+R6n+VTeqP2VZiJXdOv8LwJ1Qm8yRWnkep/lM3qj9ldLBN2NHTPEry+pcwgtEuXICOByNADj43U5RSlqbZLDkziorTykYssoioLQiIgCIiAIiIAq233/AJrTf2/6qRWSq333fmtN/eP1civ0v+aPvKdT/il7iU7EtH8HUOg/Nqfl/wBNq4O9vDoXUL5y1olhdF0bwAHdaRrS2/MEE6dyimC1W0Ap4BTRkwCOPoSG0x/J5Rk8434W46rj7VS4o7o3YoyboWuHVAjYzs0dGC0OIuATfitFWnatUuZdfB7lFly7PHK+nkWdupe44bBm+C6YNv8AFEjrej9i3dptsqTD7NmcXSEXEUYzPI7TwDR4kL02LxGmqKSM0gyRxgR9GfOYWjzXd/O/O91wotgadlXNW1cvuhjznayfKA1xJuXng8AZQ0WFhe99FnfI7JOe3Xb5Fy5lCKh6mrTb3qNzgHQzsHxvybreIDr/AHqdYZiUVTG2aB4kY/g5vdxBHEEdij+LfwRURuhkfS2IsC18TXNPa1wOhCiG5mocyprKYOzxhuYEcCWPyZx85pb6gpOuEoOUE015kVZKM1GTTyTXFtsoKarioXslMk/Q5XNDSwdK4tbclwPEG+i5uO7zaKleYm56hzSQ4xZcoI4jM4i58LqF72s/8Jx9HcSGKnDCDY5i+QNseWpCsfZnY2lo4Ws6JkkhaOkke0OLjz48G9gUpVVQhGUsvK6BTsnOUY+D6nlsvt7S17ujZnil1IjlABcBxLS0kHw49y896/vZUeMP4rFA9ucNjw/FKSSlHRCQwyZG6AO6XK7KOQItp3ntU83re9lR4w/isXezjGyuUOjx+pznk4TUuq/Y+d0p/iyD51R+M9fe0G3tNRzimLZZ5Ta7IGtdZx81hzOHWPZ9yg2G7Y+4MJgggINVKajKOPRtMz+uRzPxRzNuXGSbudijB/8AtrAXVMly1rjcx5uLiechubnle3au2VRUpTs6ZeF5/wAHITbjGEPJZJ9TyFzWuLSwuAJa61xpwNiRf0r2WAFlYjWEREAREQBERAEREAREQBERAEREAVb77vzWm/t/1UiscqA73sNnqaenZTxPmc2bMRGLkDo3i57rkK/TNK6LfmU6hZrkl5Ei2I97qD+7U/4bVu4zDG+CdswBjMcmfNwy5Te/3qqsNxfHaeKKCOkdkhYxjLwOJytAAuc2psF8VzMexIdBLE6KN1g8ZWwsI/TJOYjuHqKsem72XKKXvIdt3cKL9Da3HSOBrQScgZTuPzvymvjYfYubhdLNtFVzOmlcyCGzgxuoa1znCNrGnTMcpJcQeHhaytitmG4dTmK/SSSHNM/gHG1rC/wQNB6VXz8ExHBamSaiiNRBJcWY0yXZe4a9jes0tvoQrlbGdk3HZv8AC39dWVODjCKluvHBJxusw5rbuMptqSZLeN7BRvc3l93VfR6s6J+Qnjl6VuX7LLblqsaxYe5zB7hgfpK9zHxkt5jr9Zw7gNe1bO7bZ2eixCsD4nthayRkUrhYPAlGUg8CS0ArjnLspqyeX5Zz4nVFdpFwjhefwOft4L49Qg8L0H47lb4VXbY4RUyY1STxwSPijNFmka27RllcXXPKwN1aIWe9pxrx5fNl1McSn7yot73vhQfNi/HUu3re9lR4w/isUd3nYPUz11HJDDJKyNsedzGkhtprm58NVJ95FHJPh88ULHSvcYrMYLk2kYTYeAVnMvufZ19SDT+826/sVTHs5I2gp8Vpic8TpDKBqW9HK4NlAN9AALjuv2q29h9qGYhDn0bNHZs0Y5Hk4fonl6RyXhu3oZIsPiinjdG8GfNHILGzpXkXHeD9qh+L7M1WF1zavC4nSxPJvEwXygm74nD4h+CeRHcFKycbpShJ7pvD+RGEXUlJLZ9V8y3LrK08OqjLGyQsdEXgEskBa5p5ggrcWE2BERAEREAREQBERAEREAREQBERAEREAREQBERAEREAREQBERAEREAREQBERAEREAREQBERAEREAREQBERAEREAREQBERAEREAREQBERAEREAREQBERAEREAREQBERAEREAREQBERAEREAREQBERAEREAREQBERAEREAREQBERAEREAREQBERAEREAREQBERAEREAREQBERAEREAREQBERAEREAREQBERAEREAREQBERAEREAREQBERAEREAREQBERAEREAREQBERAEREAREQBERAEREAREQBERAEREAREQH//Z" />
                    </div>
                    <div className="experience-info">
                        <h3>Application Specialist Google Edge (AWS)</h3>
                        April 2017 - September 2018<br /><br />
                        <p>
                            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur in iaculis ex. Etiam volutpat laoreet urna. Morbi ut tortor nec nulla commodo malesuada sit amet vel lacus. Fusce eget efficitur libero. Morbi dapibus porta quam laoreet placerat.
                        </p>

                    </div>
                </div>

                <div className="experience shadow-large">
                    <div className="experience-image">
                        <Image alt="" width="100px" height="100px" src="data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAkGBxIQEhEQEBMWEBMPFhAVExISFxUWFxcXFhYWGBYWFxUYHSggGBolHRUVITEiMSotLi4uFyAzODMsNygtLisBCgoKDg0OGxAQGy4mICYtLS0tLy0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLf/AABEIAOEA4QMBIgACEQEDEQH/xAAcAAEAAgMBAQEAAAAAAAAAAAAABgcBBAUDAgj/xABOEAABAwIDBAUFCwYNBQEAAAABAAIDBBEFEiEGBzFBEyJRYXEXMoGR0hQ1QlJUcpKTobGzIzRiw9HTFSUzQ0RTc3SEosHC4WOCg7LwJP/EABoBAQADAQEBAAAAAAAAAAAAAAACAwQBBQb/xAA0EQACAgECAwUFBwUBAAAAAAAAAQIDEQQhBRIxEyJBUZFhcYHB8BQjMqGx0eEVJDNScgb/2gAMAwEAAhEDEQA/ALxREQBERAEREAREQBERAEREAREQBERAEREAREQBERAEREAREQBERAEREAREQBERAEREAREQBERAEREAREQBERAEREAREQBERAEREAREQBERAEREAREQBERAEREAREQBERAEREAREQBERAEREAREQBERAEREAREQBERAEREAREQBERAEREAREQBERAEREAREQBERAEREAREQBERAEREAREQBERAEREAREQGCovtxtG/D4o5GRtlL3ltnEi3Vc6+gPYpQVyMcwOGsEbZwXNieXhoJAJsRrbiNVGabXd6l2nlVG2LtWY53XmV0d684407B4uf7KeVefnTx/Tf7KsmkwOliAEdPEy3xY2/fbVUtvDYG4hUhoDQOj0AsP5NvJZbO1hHPMfR8Pjw/WXdmqMbZzzP9yQnezN8nj+m72V6U29Gd72M9zsGcsFw5+mZwF/N71Id2VFG/D4i+Njznm1c0H+cd2hdOv2OopiHdAyJ7S1wfCBGbtIIvl0PDmpqNrSfMZLr+HV2zqlRjDaypN7rxxlfqc3bnaybDnwhkTJWTB2rnFpBba40B0s4epRnyszj+jxn/AL3+ytvfT/RP8R/sWvudha51VnaH2bDbOAebr8fQozlPteVMv0+m0kOG/abK+Zp+bWd8efyPPysT8qdn0n+ypzsXtA6vpzO9gjIkezK0kjqgG9yO9blbglJN1ZYIXk9rG38QbXHivjDMGjoYZY6cENJkkDSS6zi0aC/LRXQjYn3pZR5mqv0dlWKquSWV4trHj1ODtTvChpXuhhYZ5WaO1ysaewu5nuCinlKrnklkUdv0Y5H/AOYPUKglHStfN125w6RvN3XBeNeZ1V44Ttdhz2Bsc0UIAsI32iI7spss8LJWN97B6+q0VGgrj9y7G1vJt4Xp+WSDU+9SqBtJDE+3HKHsP3lWHsjj4r4OnDDHZzmFpN9W21B7NV9VuG0Vc2z2RTg/CblLh3h7dQfSvPZ/B48OhlY15dGHSSgu4tBAuCedrFXxjOL3eUeTqrtHbV93VyTyvHKa+vYbmN45BRs6Sd4YOQ4ucexrRqSq+xLeu65FNAMo4Oldf/K3h61CdosZkrZ3zSE2JLWtPBjOQA+096sfd5sbEyKOrqGCSWUZmNeLhjT5vVOmY8b96q7SdkuWOyPTlw7S6DTq3VJyk+kei93w8SPHeVX2zdHFl7ejkt9LMpLsTtzLWz+55YmN6jn52E8iBax8e1Twxi1rC3ZYWXDh2ep4JzVxNEJyPa8MsGuBscxA4Hq8Rx5qxVzTT5snnWavR2Vyj2HLLHdabe/14m5jWNwUcfSTvyDgBxc49jW8SVXuJb1X3Ip4BlHB0pJP0W/tUN2qxt1dUPmceoHFsbeTWA6W7zxP/CsLdtsnG2FlXOwPkl60YeLhjeRAPwjxv3qvtZ2S5YbI9F8O02h06u1S5pPpHovrzZwfKXXt6zo4g3vje0evMu1g+9KNxDauIxX/AJyM52jvIOoHrVhzQNe0tc0OB4ggEeoqnN5OyzKN7JoBlhmJBYODH8er2NIvp3KU1ZWubmyV6OWg1s+xlVyN9GmXDSVTJWtfG4Pa8Xa5pBBHaCFsqm91OPujnFI43jnzFoPBsgF9OwOAPpCuMK6uxTjk8nX6OWkudTefFPzX11MoiKZjCIiAIiIAsWWUQGLKhd4/vhU/+L8MK+iqG3je+NT4x/htWbVfg+J7/wD5tf3b/wCX8iyt1vvfF8+b/wB3KX2UP3VH+Lovnz/iFTFXV/gXuR5evX91b/0/1Ku30/0T/EfcxRDZLZ6orTKKZ7YzGGF2Zz23zZreaDfgVL99B/NP8R/sXE3bbQ09C6c1Di3pBEG5Wud5pffgNOIWSzld3e6fwfT6Kd0OE81KzLLxtnx8vcSPYzY2ro6xs05ZIwRytzh7nG7sttHC/JWOVCajedQtHV6WQ9jWW+11gvrZjbF1cavLGImwRtcy5zOJOfzuXwRotEJVruxZ4Oro1t2b7oY6ZeOX2Lb+DlbVbthK981I5rS8lzon3Dcx1Ja4cL9ihdZsViEV7073gc2Frx6mm/2KY4FvRaQG1kRadLyxatPeWHUei6kke3uHOF/dLW9zg4H1EKrkps3TPShrOK6JKucOZLps3+a6lIAS079M8L2/PjePuKs3ZjaOWuoa6nkOeWGCTK8cXtcxwF/0gdPSuHvH2lpq0wtpwXGMuLpS0tuCLZRexI5+hdjdBhLwJ6l4IZK1sbL/AAgDdzvDUD0FV1Jxs5YvKNnEZxu0C1F0OWeVhePX1w14Mq53A+lfpHBZWvggczVro4yLdmUKmtutk5KKV0jGk07yS1wF8pOuR/ZzseC39htuvcjRT1AL4QSWOZq5l9cpHNv3LtMlVNxkOLVPiOnhfp98dUuu/X4ry9C5lpYswuhma3iYpQPEtNlwzt9h+XN7oHzcr830bXWlgO2gr6zoIWFsLY5HFzx1nEFoFh8Eanv8Fr7SPTJ8vHR6jDnyPEd3lY/UpS2vp/1X6L2Yka+kpnM80xRWt3NAVTbfbJvpZXTxtJgkcXXb8BxNy13YL6g+jRbWwe3Ao2+5qgExXJa5upZfiC3m2/ZwWOl9lNxkfUcVrfEtLC7T746pdd+vxXl8S5FAt8EjRRsafOdMzL6GvJ+xdKbeDh7WZhOH/osa4u9VtFVm2G0r8QlDsuSNl2xxg3Op1c63wjp/yr77YqDWTyeEcOvnqY2Si1GLy29un8njsPGXV1IG/wBcD6ACT9l1+hAq13YbKPhPu2oaWPcC2Fh4taeL3DkTwA7PFWUE08HGG/iR47qoajU9zdRWM+by8/sZREWg8UIiIAiIgCIvl5sL9iAyVEq/d/RTyPmk6UvkcXOPSOGp7uQUa2o3qZHuioWNkDCQZ5LlpI+I1pFx339Cj/lWxDsp/q3+2tK0Ns45x6lcOI9hJ8k2n7C3MAwKGijdFBmyOcXWe4usTa9ieHBdYlUaN6uI9kH1b/bVm7Iy4hKzpa/oo8wuyGNhDgDze4uNj3KNumnUu9j1OR1Suk3u34s9cf2Sp657Hz9ITGCGhry0AE3Og5nT1Ll+TLD+yX6w/sWNtdvY6A9DG0T1BAJZezWA8C89vdx8FAjvWxDk2nHd0b/bXIaGdq5lH1L/AOq2ULs42SSXgmyfeTLD+yX6w/sXVwHZOloel6AO/LBofncXXAvYa/OKqzyq4h2U/wBW721LdicbxTECJZOhhpwfP6J2Z9uIjBfbxdw8V2ehdS52kvicfFbb1yOcn7NzqVm7egkNwx8X9k8gfRNwFondVScp6gemL92pLtNtHDh8JlmNydI4x5z3djR954BVbU72K1ziY44I28mua959LswufQqqtC7lmMUXvjOoo27WXqTvDt3FDCQ5zXzEf1rrj6LQAfUpZFG1gDWgNA0AFgAO4Kk/KtiHZT/Vv9tdPZ3bbF6+UQwNp9LF7zG/LG34zjn9Q4n7Vo+wTrWdkveZLOJPUSXPJyftLalia4EOAcDxBAIPoUVxLd5QTkuyOiJ49C7KL/NNx9ikJn6CEyVEjfybSZJCMje82ubD0qrcc3syl5bRRMawHR8wc5zu/ICMo8bnwVENNK94SyWR1ktM+aMnF+w73kqpb/y09vGL92u5s7sZTUT+li6R0haW5pHX0Nr6AAcuxVl5VsR7Kf6t/tr1p952JyvbHGyF75CGsY2J5LieQ66tXDJx3wvU7Zxy66PJOyTT8PMumSMOBDgCDoQbEHxCiuJbu6CYlwY6EniYXBo+iQR9i6+z7avo71z4zK63UhaWtZ3Zi45j36KH7YbzG0z3QUjGzyMNnyOJ6NrvigDVxHPUBUqh2y5Us/oIauen78ZOPu2Nhu6ykB1lqCOy8X+jF3cH2MoqUhzIszxwfIc7h4E8FWHlWxDsp/q3/vEO9bEOyn+rf+8V8eFzjuoo5bxy21cs7JNeReAC+lDNiK3EqprZ6zooYni7I2xuEjxycSX9Qei5UyCzyjyvGfQhGXMsmURFwkEREAREQGCuDtTgLq6PofdElPGfPbEG3f3OcRfL3Diu8VGNutqXYZFFKIhN0snR5S/Jbqude+U381TrUnJKPXwIzcVFuXQjfkfp/lU30Y/ZTyP0/wAqm+jH7K5/lhf8jH15/dLcwze7E5wbUwOhbcXex4kDR2ublabeF1tf2xb5f5GRPTPbH5M7+zm72koniUZp5G+a6XKQ09rWgAA9/FSXEad8kbmRymBztBI0Bxb4B2l17U8zZGtewhzXAFrhqCDqCD2L1WGU5SeZPLNcYRisRWxWsm6OFxLnVc7nOJLnOEZJJ4kkjUrHkfg+VTeqP2VZd1lXfarv9iv7PV/qV7h+6ejjcHSySzga5HFrWnudlAJHddTyKEMaGMAa1os0AWAA4AAcl7LF1VZZOzeTyTjCMfwogWM7txWSmaorZ3uOgGWMNa34rG5eqP8A43Wj5H6f5VN6o/ZVmLhbZ4y6hpJKljRI6PIMriQDme1vEeKthfdtGMiudNe8miJxboKYEZqmdw5gdGL918qm2B4LBRRiGnYGNGp5ucfjOcdXHvWnsXjTq+kjqXsEbnmQZWkkDI9zRqfmrvqNttsnyzb2JVwglmKIptXsicRIElVLFE2xEMYZlJ+M64u49nIKPeR+D5VN9GP2VZiLkL7ILEXhHZUwk8yRWg3P0/yqb1R+ypNszsXS4f1oWl8pFjNJZz7cwLABo8ApKiTvsmsSkI01xeUjk7QYW+qiMTJ30wdo58QbnI+KHHzfEaqE+R6n+VTeqP2VZiJXdOv8LwJ1Qm8yRWnkep/lM3qj9ldLBN2NHTPEry+pcwgtEuXICOByNADj43U5RSlqbZLDkziorTykYssoioLQiIgCIiAIiIAq233/AJrTf2/6qRWSq333fmtN/eP1civ0v+aPvKdT/il7iU7EtH8HUOg/Nqfl/wBNq4O9vDoXUL5y1olhdF0bwAHdaRrS2/MEE6dyimC1W0Ap4BTRkwCOPoSG0x/J5Rk8434W46rj7VS4o7o3YoyboWuHVAjYzs0dGC0OIuATfitFWnatUuZdfB7lFly7PHK+nkWdupe44bBm+C6YNv8AFEjrej9i3dptsqTD7NmcXSEXEUYzPI7TwDR4kL02LxGmqKSM0gyRxgR9GfOYWjzXd/O/O91wotgadlXNW1cvuhjznayfKA1xJuXng8AZQ0WFhe99FnfI7JOe3Xb5Fy5lCKh6mrTb3qNzgHQzsHxvybreIDr/AHqdYZiUVTG2aB4kY/g5vdxBHEEdij+LfwRURuhkfS2IsC18TXNPa1wOhCiG5mocyprKYOzxhuYEcCWPyZx85pb6gpOuEoOUE015kVZKM1GTTyTXFtsoKarioXslMk/Q5XNDSwdK4tbclwPEG+i5uO7zaKleYm56hzSQ4xZcoI4jM4i58LqF72s/8Jx9HcSGKnDCDY5i+QNseWpCsfZnY2lo4Ws6JkkhaOkke0OLjz48G9gUpVVQhGUsvK6BTsnOUY+D6nlsvt7S17ujZnil1IjlABcBxLS0kHw49y896/vZUeMP4rFA9ucNjw/FKSSlHRCQwyZG6AO6XK7KOQItp3ntU83re9lR4w/isXezjGyuUOjx+pznk4TUuq/Y+d0p/iyD51R+M9fe0G3tNRzimLZZ5Ta7IGtdZx81hzOHWPZ9yg2G7Y+4MJgggINVKajKOPRtMz+uRzPxRzNuXGSbudijB/8AtrAXVMly1rjcx5uLiechubnle3au2VRUpTs6ZeF5/wAHITbjGEPJZJ9TyFzWuLSwuAJa61xpwNiRf0r2WAFlYjWEREAREQBERAEREAREQBERAEREAVb77vzWm/t/1UiscqA73sNnqaenZTxPmc2bMRGLkDo3i57rkK/TNK6LfmU6hZrkl5Ei2I97qD+7U/4bVu4zDG+CdswBjMcmfNwy5Te/3qqsNxfHaeKKCOkdkhYxjLwOJytAAuc2psF8VzMexIdBLE6KN1g8ZWwsI/TJOYjuHqKsem72XKKXvIdt3cKL9Da3HSOBrQScgZTuPzvymvjYfYubhdLNtFVzOmlcyCGzgxuoa1znCNrGnTMcpJcQeHhaytitmG4dTmK/SSSHNM/gHG1rC/wQNB6VXz8ExHBamSaiiNRBJcWY0yXZe4a9jes0tvoQrlbGdk3HZv8AC39dWVODjCKluvHBJxusw5rbuMptqSZLeN7BRvc3l93VfR6s6J+Qnjl6VuX7LLblqsaxYe5zB7hgfpK9zHxkt5jr9Zw7gNe1bO7bZ2eixCsD4nthayRkUrhYPAlGUg8CS0ArjnLspqyeX5Zz4nVFdpFwjhefwOft4L49Qg8L0H47lb4VXbY4RUyY1STxwSPijNFmka27RllcXXPKwN1aIWe9pxrx5fNl1McSn7yot73vhQfNi/HUu3re9lR4w/isUd3nYPUz11HJDDJKyNsedzGkhtprm58NVJ95FHJPh88ULHSvcYrMYLk2kYTYeAVnMvufZ19SDT+826/sVTHs5I2gp8Vpic8TpDKBqW9HK4NlAN9AALjuv2q29h9qGYhDn0bNHZs0Y5Hk4fonl6RyXhu3oZIsPiinjdG8GfNHILGzpXkXHeD9qh+L7M1WF1zavC4nSxPJvEwXygm74nD4h+CeRHcFKycbpShJ7pvD+RGEXUlJLZ9V8y3LrK08OqjLGyQsdEXgEskBa5p5ggrcWE2BERAEREAREQBERAEREAREQBERAEREAREQBERAEREAREQBERAEREAREQBERAEREAREQBERAEREAREQBERAEREAREQBERAEREAREQBERAEREAREQBERAEREAREQBERAEREAREQBERAEREAREQBERAEREAREQBERAEREAREQBERAEREAREQBERAEREAREQBERAEREAREQBERAEREAREQBERAEREAREQBERAEREAREQBERAEREAREQBERAEREAREQBERAEREAREQBERAEREAREQBERAEREAREQBERAEREAREQH//Z" />
                    </div>
                    <div className="experience-info">
                        <h3>Application Analyst</h3>
                        July 2015 - June 2016<br /><br />
                        <p>
                            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur in iaculis ex. Etiam volutpat laoreet urna. Morbi ut tortor nec nulla commodo malesuada sit amet vel lacus. Fusce eget efficitur libero. Morbi dapibus porta quam laoreet placerat.
                        </p>

                    </div>
                </div>

                <div className="experience shadow-large">
                    <div className="experience-image">
                        <Image alt="" width="100px" height="100px" src="https://capitahealthcaredecisions.com/module/uploads/2019/04/Capitalogo-chdwebsite-blog.png" />
                    </div>
                    <div className="experience-info">
                        <h3>Voice Business Analyst</h3>
                        November 2013 - July 2015<br /><br />
                        <p>
                            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur in iaculis ex. Etiam volutpat laoreet urna. Morbi ut tortor nec nulla commodo malesuada sit amet vel lacus. Fusce eget efficitur libero. Morbi dapibus porta quam laoreet placerat.
                        </p>

                    </div>
                </div>
            </div>
        </div>
    </div>

    <div id="education">
        <h2 className="heading">Education</h2>
        <div className="education-block">
            <h3>Clackmannan College of Further Education</h3>
            <span className="education-date">September 2003 - May 2005</span>
            <h4>HND Computer and Network Support</h4>
            <ul>
                <li>
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                </li>
                <li>
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                </li>
                <li>
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                </li>
            </ul>
        </div>
    </div>

    <div id="projects" className="background-alt">
        <h2 className="heading">Certifications</h2>
        <div className="container">
            <div className="row">
                <div className="project shadow-large">
                    <div className="project-image">
                        <Image alt="" width="100px" height="100px" src="https://d1.awsstatic.com/training-and-certification/Certification%20Badges/AWS-Certified_Solutions-Architect_Associate_badge_512x512.139edbefd4d7e9a16213032f592bdd8ca769dced.png" />
                    </div>
                    <div className="project-info">
                        <h3>AWS Solutions Architect</h3>
                        <p>
                            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur in iaculis ex. Etiam volutpat laoreet urna. Morbi ut tortor nec nulla commodo malesuada sit amet vel lacus. Fusce eget efficitur libero. Morbi dapibus porta quam laoreet placerat.
                        </p>

                    </div>
                </div>

                <div className="project shadow-large">
                    <div className="project-image">
                        <Image alt="" width="100px" height="100px" src="https://d1.awsstatic.com/training-and-certification/Certification%20Badges/AWS-Certified_Sysops-Administrator_Associate_512x512.7ee4f9e7f4046349a3bfe27dcb1a54a340e04623.png" />
                    </div>
                    <div className="project-info">
                        <h3>AWS Sysops</h3>
                        <p>
                            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur in iaculis ex. Etiam volutpat laoreet urna. Morbi ut tortor nec nulla commodo malesuada sit amet vel lacus. Fusce eget efficitur libero. Morbi dapibus porta quam laoreet placerat.
                        </p>

                    </div>
                </div>
            </div>
        </div>
    </div>

    <div id="skills">
        <h2 className="heading">Skills</h2>
        <ul>
            <li>Groovy</li>
            <li>Ansible</li>
            <li>Shell</li>
            <li>Terraform</li>
            <li>Problem Solving</li>
        </ul>
    </div>

    <div id="contact">
        <h2>Contact Me</h2>
        <div id="contact-form">
            <form method="POST" action="https://formspree.io/email@email.com">
                <input type="hidden" name="_subject" value="Contact request from personal website" />
                <input type="email" name="_replyto" placeholder="Your email" required />
                <textarea name="message" placeholder="Your message" required></textarea>
                <button type="submit">Send</button>
            </form>
        </div>
    </div>
    <Footer />
    </main>
  );
}
